    {"BMS_BattCellNum1Vol", 2, SIG_INT},
    {"BMS_BattCellNum2Vol", 2, SIG_INT},
    {"BMS_BattCellNum3Vol", 2, SIG_INT},
    {"BMS_BattCellNum4Vol", 2, SIG_INT},
    {"BMS_BattCellNum5Vol", 2, SIG_INT},
    {"BMS_BattCellNum6Vol", 2, SIG_INT},
    {"BMS_BattCellNum7Vol", 2, SIG_INT},
    {"BMS_BattCellNum8Vol", 2, SIG_INT},
    {"BMS_BattCellNum9Vol", 2, SIG_INT},
    {"BMS_BattCellNum10Vol", 2, SIG_INT},

    {"BMS_BattCellNum11Vol", 2, SIG_INT},
    {"BMS_BattCellNum12Vol", 2, SIG_INT},
    {"BMS_BattCellNum13Vol", 2, SIG_INT},
    {"BMS_BattCellNum14Vol", 2, SIG_INT},
    {"BMS_BattCellNum15Vol", 2, SIG_INT},
    {"BMS_BattCellNum16Vol", 2, SIG_INT},
    {"BMS_BattCellNum17Vol", 2, SIG_INT},
    {"BMS_BattCellNum18Vol", 2, SIG_INT},
    {"BMS_BattCellNum19Vol", 2, SIG_INT},
    {"BMS_BattCellNum20Vol", 2, SIG_INT},

    {"BMS_BattCellNum21Vol", 2, SIG_INT},
    {"BMS_BattCellNum22Vol", 2, SIG_INT},
    {"BMS_BattCellNum23Vol", 2, SIG_INT},
    {"BMS_BattCellNum24Vol", 2, SIG_INT},
    {"BMS_BattCellNum25Vol", 2, SIG_INT},
    {"BMS_BattCellNum26Vol", 2, SIG_INT},
    {"BMS_BattCellNum27Vol", 2, SIG_INT},
    {"BMS_BattCellNum28Vol", 2, SIG_INT},
    {"BMS_BattCellNum29Vol", 2, SIG_INT},
    {"BMS_BattCellNum30Vol", 2, SIG_INT},

    {"BMS_BattCellNum31Vol", 2, SIG_INT},
    {"BMS_BattCellNum32Vol", 2, SIG_INT},
    {"BMS_BattCellNum33Vol", 2, SIG_INT},
    {"BMS_BattCellNum34Vol", 2, SIG_INT},
    {"BMS_BattCellNum35Vol", 2, SIG_INT},
    {"BMS_BattCellNum36Vol", 2, SIG_INT},
    {"BMS_BattCellNum37Vol", 2, SIG_INT},
    {"BMS_BattCellNum38Vol", 2, SIG_INT},
    {"BMS_BattCellNum39Vol", 2, SIG_INT},
    {"BMS_BattCellNum40Vol", 2, SIG_INT},

    {"BMS_BattCellNum41Vol", 2, SIG_INT},
    {"BMS_BattCellNum42Vol", 2, SIG_INT},
    {"BMS_BattCellNum43Vol", 2, SIG_INT},
    {"BMS_BattCellNum44Vol", 2, SIG_INT},
    {"BMS_BattCellNum45Vol", 2, SIG_INT},
    {"BMS_BattCellNum46Vol", 2, SIG_INT},
    {"BMS_BattCellNum47Vol", 2, SIG_INT},
    {"BMS_BattCellNum48Vol", 2, SIG_INT},
    {"BMS_BattCellNum49Vol", 2, SIG_INT},
    {"BMS_BattCellNum50Vol", 2, SIG_INT},

    {"BMS_BattCellNum51Vol", 2, SIG_INT},
    {"BMS_BattCellNum52Vol", 2, SIG_INT},
    {"BMS_BattCellNum53Vol", 2, SIG_INT},
    {"BMS_BattCellNum54Vol", 2, SIG_INT},
    {"BMS_BattCellNum55Vol", 2, SIG_INT},
    {"BMS_BattCellNum56Vol", 2, SIG_INT},
    {"BMS_BattCellNum57Vol", 2, SIG_INT},
    {"BMS_BattCellNum58Vol", 2, SIG_INT},
    {"BMS_BattCellNum59Vol", 2, SIG_INT},
    {"BMS_BattCellNum60Vol", 2, SIG_INT},

    {"BMS_BattCellNum61Vol", 2, SIG_INT},
    {"BMS_BattCellNum62Vol", 2, SIG_INT},
    {"BMS_BattCellNum63Vol", 2, SIG_INT},
    {"BMS_BattCellNum64Vol", 2, SIG_INT},
    {"BMS_BattCellNum65Vol", 2, SIG_INT},
    {"BMS_BattCellNum66Vol", 2, SIG_INT},
    {"BMS_BattCellNum67Vol", 2, SIG_INT},
    {"BMS_BattCellNum68Vol", 2, SIG_INT},
    {"BMS_BattCellNum69Vol", 2, SIG_INT},
    {"BMS_BattCellNum70Vol", 2, SIG_INT},

    {"BMS_BattCellNum71Vol", 2, SIG_INT},
    {"BMS_BattCellNum72Vol", 2, SIG_INT},
    {"BMS_BattCellNum73Vol", 2, SIG_INT},
    {"BMS_BattCellNum74Vol", 2, SIG_INT},
    {"BMS_BattCellNum75Vol", 2, SIG_INT},
    {"BMS_BattCellNum76Vol", 2, SIG_INT},
    {"BMS_BattCellNum77Vol", 2, SIG_INT},
    {"BMS_BattCellNum78Vol", 2, SIG_INT},
    {"BMS_BattCellNum79Vol", 2, SIG_INT},
    {"BMS_BattCellNum80Vol", 2, SIG_INT},

    {"BMS_BattCellNum81Vol", 2, SIG_INT},
    {"BMS_BattCellNum82Vol", 2, SIG_INT},
    {"BMS_BattCellNum83Vol", 2, SIG_INT},
    {"BMS_BattCellNum84Vol", 2, SIG_INT},
    {"BMS_BattCellNum85Vol", 2, SIG_INT},
    {"BMS_BattCellNum86Vol", 2, SIG_INT},
    {"BMS_BattCellNum87Vol", 2, SIG_INT},
    {"BMS_BattCellNum88Vol", 2, SIG_INT},
    {"BMS_BattCellNum89Vol", 2, SIG_INT},
    {"BMS_BattCellNum90Vol", 2, SIG_INT},

    {"BMS_BattCellNum91Vol", 2, SIG_INT},
    {"BMS_BattCellNum92Vol", 2, SIG_INT},
    {"BMS_BattCellNum93Vol", 2, SIG_INT},
    {"BMS_BattCellNum94Vol", 2, SIG_INT},
    {"BMS_BattCellNum95Vol", 2, SIG_INT},
    {"BMS_BattCellNum96Vol", 2, SIG_INT},

    {"BMS_BattTempSensorNum1", 1, SIG_INT},
    {"BMS_BattTempSensorNum2", 1, SIG_INT},
    {"BMS_BattTempSensorNum3", 1, SIG_INT},
    {"BMS_BattTempSensorNum4", 1, SIG_INT},
    {"BMS_BattTempSensorNum5", 1, SIG_INT},
    {"BMS_BattTempSensorNum6", 1, SIG_INT},
    {"BMS_BattTempSensorNum7", 1, SIG_INT},
    {"BMS_BattTempSensorNum8", 1, SIG_INT},
    {"BMS_BattTempSensorNum9", 1, SIG_INT},
    {"BMS_BattTempSensorNum10", 1, SIG_INT},

    {"BMS_BattTempSensorNum11", 1, SIG_INT},
    {"BMS_BattTempSensorNum12", 1, SIG_INT},
    {"BMS_BattTempSensorNum13", 1, SIG_INT},
    {"BMS_BattTempSensorNum14", 1, SIG_INT},
    {"BMS_BattTempSensorNum15", 1, SIG_INT},
    {"BMS_BattTempSensorNum16", 1, SIG_INT},
    {"BMS_BattTempSensorNum17", 1, SIG_INT},
    {"BMS_BattTempSensorNum18", 1, SIG_INT},
    {"BMS_BattTempSensorNum19", 1, SIG_INT},
    {"BMS_BattTempSensorNum20", 1, SIG_INT},

    {"BMS_BattTempSensorNum21", 1, SIG_INT},
    {"BMS_BattTempSensorNum22", 1, SIG_INT},
    {"BMS_BattTempSensorNum23", 1, SIG_INT},
    {"BMS_BattTempSensorNum24", 1, SIG_INT},
    {"BMS_BattTempSensorNum25", 1, SIG_INT},
    {"BMS_BattTempSensorNum26", 1, SIG_INT},
    {"BMS_BattTempSensorNum27", 1, SIG_INT},
    {"BMS_BattTempSensorNum28", 1, SIG_INT},
    {"BMS_BattTempSensorNum29", 1, SIG_INT},
    {"BMS_BattTempSensorNum30", 1, SIG_INT},

    {"BMS_BattTempSensorNum31", 1, SIG_INT},
    {"BMS_BattTempSensorNum32", 1, SIG_INT},
    {"BMS_BattTempSensorNum33", 1, SIG_INT},
    {"BMS_BattTempSensorNum34", 1, SIG_INT},
    {"BMS_BattTempSensorNum35", 1, SIG_INT},
    {"BMS_BattTempSensorNum36", 1, SIG_INT},
    {"BMS_BattTempSensorNum37", 1, SIG_INT},
    {"BMS_BattTempSensorNum38", 1, SIG_INT},
    {"BMS_BattTempSensorNum39", 1, SIG_INT},
    {"BMS_BattTempSensorNum40", 1, SIG_INT},

    {"BMS_MaxCellNo", 1, SIG_INT},
    {"BMS_MaxCellU", 2, SIG_INT},
    {"BMS_MinCellNo", 1, SIG_INT},
    {"BMS_MinCellU", 2, SIG_INT},

    {"BMS_MaxTempNo", 1, SIG_INT},
    {"BMS_MaxTemp", 1, SIG_INT},
    {"BMS_MinTempNo", 1, SIG_INT},
    {"BMS_MinTemp", 1, SIG_INT},

    {"MCU_MotorSpeed", 2, SIG_INT},
    {"MCU_ControllerTorque", 2, SIG_INT},
    {"MCU_DC_linkVoltage", 2, SIG_INT},
    {"MCU_DC_linkCurrent", 2, SIG_INT},

    {"MCU_InverterTemp", 1, SIG_INT},
    {"MCU_MotorTemp", 1, SIG_INT},

    {"VCU_BPCAN_VehicleSpeed", 2, SIG_INT},

    {"VCU_BPCAN_OutTemp", 1, SIG_INT},
    {"VCU_ALLCAN_AccPed_Pos", 1, SIG_INT},
    {"VCU_ALLCAN_BrkPed_Pos", 1, SIG_INT},
    {"DCDC_RealTemperature", 1, SIG_INT},

    {"ICM_ODOTotal", 3, SIG_INT},

    {"BMS_PackU", 2, SIG_INT},
    {"BMS_PackI", 2, SIG_INT},
    {"BMS_PackSoc", 1, SIG_INT},

    {"MCU_ControllerTorqueValid", 1, SIG_INT},
    {"BMS_PackSoh", 1, SIG_INT},
    {"BMS_Insulation_R", 2, SIG_INT},
    {"BMS_DischargeInstantPower", 1, SIG_INT},
    {"MCU_MotorSpeedValid", 1, SIG_INT},
    {"VCU_BPCAN_PowerConsumption", 2, SIG_INT},
    {"VCU_BPCAN_Mileage", 2, SIG_INT},
    {"VCU_ALLCAN_BrkPedPos_Valid", 1, SIG_INT},
    {"VCU_ALLCAN_AccPedPos_Valid", 1, SIG_INT},
    {"BMS_CCTemp1", 1, SIG_INT},
    {"BMS_CCTemp2", 1, SIG_INT},
    {"BMS_BattManuYear", 1, SIG_INT},
    {"BMS_BattManuMonth", 1, SIG_INT},
    {"BMS_BattManuDay", 1, SIG_INT},
    {"BMS_BattCodeLenth", 1, SIG_INT},
    {"BMS_BattCodeStartN", 1, SIG_INT},
    {"BMS_BattCodeStartNCode", 1, SIG_INT},
    {"BMS_BattCodeStartN_1Code", 1, SIG_INT},
    {"BMS_BattCodeStartN_2Code", 1, SIG_INT},
    {"BMS_BattCodeStartN_3Code", 1, SIG_INT},
    {"BMS_BattCodeStartN_4Code", 1, SIG_INT},
    {"BMS_BattCodeStartN_5Code", 1, SIG_INT},
    {"BMS_BattSerialNumber", 2, SIG_INT},
    {"HU_StopAlarm", 1, SIG_INT},
    {"HU_DoorControl", 1, SIG_INT},
    {"HU_TrunkUnlock", 1, SIG_INT},
    {"HU_COMP_Control_Cool", 1, SIG_INT},
    {"HU_COMP_Control_Warn", 1, SIG_INT},
    {"HU_Hazard_Control", 1, SIG_INT},
    {"HU_Horn_Control", 1, SIG_INT},
    {"HU_RemoteCharge", 1, SIG_INT},
    {"HU_PowerRecycle", 1, SIG_INT},
    {"HU_TimeSyncSts", 1, SIG_INT},
    {"HU_PowerOn_Req", 1, SIG_INT},
    {"HU_WorkModeCMD", 1, SIG_INT},
    {"HU_TimeSyncData", 2, SIG_INT},
    {"HU_AudioSA", 1, SIG_INT},
    {"HU_ECOmode", 1, SIG_INT},
    {"HU_FastChargeMode", 1, SIG_INT}
